pod-gateway:
#  image:
#    repository: ghcr.io/angelnu/pod-gateway
#    tag: "latest"
  settings:
    NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.0.0/16"
    VPN_BLOCK_OTHER_TRAFFIC: true
    VPN_INTERFACE: wg0
  addons:
    vpn:
      enabled: true
      type: wireguard
